### ISSUE TITLE
Web app for project

### ISSUE THREAD

**Issue by w3slley** [edrdo/dbdia#6]
Hey! Wouldn't it be a good extension to the project to create a basic web application that based on the user input in the front end generates the ER model images in the back end and then displays it to the user? Maybe something similar to what already exists for markdown processing (https://dillinger.io/ for example), but using the dbdia syntax to create them.

Thanks!

**Comment by edrdo** [comment]
Yes, good idea, I also have that in mind. It'll have to wait though ...
